# Generated by Django 5.1.5 on 2025-02-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservices',
            name='service_search_count',
            field=models.IntegerField(default=0),
        ),
    ]
