# Generated by Django 5.1.5 on 2025-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntoapp', '0002_userservices_service_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
