# Generated by Django 5.1.5 on 2025-05-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntoapp', '0004_customuser_is_company_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_company',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
