# Generated by Django 5.2.1 on 2025-06-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntoapp', '0006_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
