# Generated by Django 5.2.1 on 2025-06-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conntoapp', '0007_company_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password2',
        ),
    ]
