# Generated by Django 5.2.1 on 2026-07-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntoapp', '0010_coursecenter_teacher_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userawards',
            name='award_name',
            field=models.CharField(max_length=1000, verbose_name='Sertifika/Ödül Adı'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='degree',
            field=models.CharField(choices=[('Bachelor’s Degree', 'Lisans'), ('Master’s Degree', 'Yüksek Lisans'), ('Ph.D.', 'Doktora')], max_length=100, verbose_name='Derece'),
        ),
    ]
