# Generated by Django 5.2.1 on 2026-07-09 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntoapp', '0012_simplify_userworks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userblogs',
            options={'verbose_name': 'Blog Yazısı', 'verbose_name_plural': 'Blog Yazıları'},
        ),
        migrations.AlterModelOptions(
            name='userworks',
            options={'verbose_name': 'Ders Materyali', 'verbose_name_plural': 'Ders Materyalleri'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/', verbose_name='Profil Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter (X)'),
        ),
        migrations.AlterField(
            model_name='userblogs',
            name='blog_category',
            field=models.CharField(max_length=100, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='userblogs',
            name='blog_content',
            field=models.TextField(max_length=5000, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='userblogs',
            name='blog_date',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='userblogs',
            name='blog_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='userblogs',
            name='blog_title',
            field=models.CharField(max_length=100, verbose_name='Blog Başlığı'),
        ),
        migrations.AlterField(
            model_name='userblogs',
            name='blog_view',
            field=models.SmallIntegerField(default=0, verbose_name='Görüntülenme'),
        ),
        migrations.CreateModel(
            name='TeacherFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_teachers', to='conntoapp.coursecenter', verbose_name='Kurs Merkezi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL, verbose_name='Öğretmen')),
            ],
            options={
                'verbose_name': 'Favori Öğretmen',
                'verbose_name_plural': 'Favori Öğretmenler',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'course_center'), name='unique_teacher_favorite_per_center')],
            },
        ),
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Puan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_ratings', to='conntoapp.coursecenter', verbose_name='Kurs Merkezi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Öğretmen')),
            ],
            options={
                'verbose_name': 'Öğretmen Puanı',
                'verbose_name_plural': 'Öğretmen Puanları',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'course_center'), name='unique_teacher_rating_per_center')],
            },
        ),
    ]
