# Generated by Django 5.2.1 on 2026-07-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conntoapp', '0016_increase_phone_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Açıklama'),
        ),
    ]
